FROM node:10

WORKDIR /usr/src/app

# Optionally copy package.json and package-lock.json files, if they exist
COPY package*.json* ./

# Install creat-react-app
RUN npm install -g create-react-app

RUN npm install

COPY . .

CMD [ "npm", "run", "dev" ]
